groups:
  - dest: '~/Project'
    repos:
      - git@github.com:kijimaD/my_go
      - git@github.com:kijimaD/digger_rs
      - git@github.com:kijimaD/cloner
      - git@github.com:kijimaD/gclone
  - dest: '~/ProjectOrg/emacs'
    repos:
      - git@github.com:kd-collective/emacs
      - git@github.com:kd-collective/corfu
      - git@github.com:kd-collective/crux
      - git@github.com:kd-collective/magit
      - git@github.com:kd-collective/git-link
      - git@github.com:kd-collective/forge
      - git@github.com:kd-collective/melpa
      - git@github.com:kd-collective/org-roam
      - git@github.com:kd-collective/projectile
      - git@github.com:kd-collective/vterm-toggle
      - git@github.com:kd-collective/hydra
      - git@github.com:kd-collective/docker.el
  - dest: '~/ProjectOrg/rust'
    repos:
      - git@github.com:kd-collective/rust
      - git@github.com:kd-collective/specs
      - git@github.com:kd-collective/shellexpand
      - git@github.com:kd-collective/dirs
      - git@github.com:kd-collective/bracket-lib
      - git@github.com:kd-collective/cargo
      - git@github.com:kd-collective/nushell
  - dest: '~/ProjectOrg/cpp'
    repos:
      - git@github.com:kd-collective/polybar
      - git@github.com:kd-collective/simutrans
  - dest: '~/ProjectOrg/c'
    repos:
      - git@github.com:kd-collective/curl
  - dest: '~/ProjectOrg/ruby'
    repos:
      - git@github.com:kd-collective/ruby
      - git@github.com:kd-collective/doctree
      - git@github.com:kd-collective/puma
      - git@github.com:kd-collective/rubocop
      - git@github.com:kd-collective/rubygems
  - dest: '~/ProjectOrg/rails'
    repos:
      - git@github.com:kd-collective/rails
      - git@github.com:kd-collective/forem
      - git@github.com:kd-collective/gitlabhq
      - git@github.com:kd-collective/mastodon
  - dest: '~/ProjectOrg/ts'
    repos:
      - git@github.com:kd-collective/login-action
  - dest: '~/ProjectOrg/go'
    repos:
      - git@github.com:kd-collective/go
      - git@github.com:kd-collective/ecspresso
      - git@github.com:kd-collective/compose
      - git@github.com:kd-collective/cli
      - git@github.com:kd-collective/buildx
      - git@github.com:kd-collective/moby
      - git@github.com:kd-collective/build-push-action
      - git@github.com:kd-collective/color
      - git@github.com:kd-collective/echo
      - git@github.com:kd-collective/godotenv
      - git@github.com:kd-collective/spinner
      - git@github.com:kd-collective/gocloc
      - git@github.com:kd-collective/octocov
      - git@github.com:kd-collective/go-github
  - dest: '~/ProjectOrg/python'
    repos:
      - git@github.com:kd-collective/guake
