[config]
host = "github"
dest_dir = "~/ProjectOrg"
repos = [
  # Emacs
  "kd-collective/emacs",
  "kd-collective/corfu",
  "kd-collective/crux",
  "kd-collective/magit",
  "kd-collective/git-link",
  "kd-collective/forge",
  "kd-collective/melpa",
  "kd-collective/org-roam",
  "kd-collective/projectile",
  "kd-collective/vterm-toggle",
  "kd-collective/hydra",
  "kd-collective/docker.el",

  # Rust
  "kd-collective/rust",
  "kd-collective/specs",
  "kd-collective/shellexpand",
  "kd-collective/dirs",
  "kd-collective/bracket-lib",
  "kd-collective/cargo",
  "kd-collective/nushell",

  # C++
  "kd-collective/polybar",
  "kd-collective/simutrans",
  # "kd-collective/Cataclysm-DDA", # big file size

  # C
  "kd-collective/curl",

  # Ruby
  "kd-collective/ruby",
  "kd-collective/doctree",
  "kd-collective/puma",
  "kd-collective/rubocop",
  "kd-collective/rubygems",

  # Ruby on Rails
  "kd-collective/rails",
  "kd-collective/forem",
  "kd-collective/gitlabhq",
  "kd-collective/mastodon",

  # TypeScript
  "kd-collective/login-action",

  # Go
  "kd-collective/go",
  "kd-collective/ecspresso",
  "kd-collective/compose",
  "kd-collective/cli",
  "kd-collective/buildx",
  "kd-collective/moby",
  "kd-collective/build-push-action",
  "kd-collective/color",
  "kd-collective/echo",
  "kd-collective/godotenv",
  "kd-collective/spinner",
]
