# https://help.ubuntu.com/community/LiveCDCustomization
# https://qiita.com/misohagi/items/4443fcc495366c717c38

on:
  push:
    # tags:
    #   - 'v*'

name: Build
env:
  CUSTOM_IMAGE_NAME: kd_ubuntu
  CUSTOM_IMAGE_ISO: ubuntu-kd-22.04.1-desktop-amd64.iso
jobs:
  build:
    name: Build .iso image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: pull base image
        run: curl -LO https://releases.ubuntu.com/jammy/ubuntu-22.04.1-desktop-amd64.iso
      - name: install essential package
        run: sudo apt install -y squashfs-tools genisoimage
      - name: mount base image
        run: mkdir mnt && sudo mount -o loop ./ubuntu-22.04.1-desktop-amd64.iso mnt
      - name: rsync
        run: mkdir extract-cd && rsync --exclude=mnt/casper/filesystem.squashfs -a mnt/ extract-cd
      - name: unsquash
        run: sudo unsquashfs mnt/casper/filesystem.squashfs && mv squashfs-root edit
      - name: copy network
        run: sudo cp /etc/resolv.conf edit/etc/resolv.conf && sudo cp /etc/hosts edit/etc/
      - name: bind
        run: sudo mount -o bind /run/ edit/run && sudo mount --bind /dev/ edit/dev
      - name: under chroot environment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cat << EOF | script -e -c 'sudo chroot edit'
          cd /tmp
          mount -t proc none /proc
          mount -t sysfs none /sys
          mount -t devpts none /dev/pts
          export HOME=/etc/skel
          export LC_ALL=C &&
          export DEBIAN_FRONTEND=noninteractive
          dbus-uuidgen | tee /var/lib/dbus/machine-id && dpkg-divert --local --rename --add /sbin/initctl && ln -s /bin/true /sbin/initctl
          mv /etc/apt/apt.conf.d/90_zsys_system_autosnapshot /etc/apt/apt.conf.d/90_zsys_system_autosnapshot.disabled
          apt upgrade -y &
          wait
          apt update &
          wait
          # ================
          ls -al
          # ビルドツール
          echo -e "\n" | apt install -y git curl make ca-certificates gnupg lsb-release
          # Rust
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          . /etc/skel/.cargo/env # $HOMEの/etc/skelにインストールされる
          # Go
          curl -OL https://go.dev/dl/go1.17.6.linux-amd64.tar.gz
          tar -C /usr/local -xzf go1.17.6.linux-amd64.tar.gz
          export PATH=$PATH:/usr/local/go/bin
          # Docker
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
          apt update
          echo -e "\n" | apt install -y docker-ce docker-ce-cli containerd.io
          # docker-compose
          curl -L https://github.com/docker/compose/releases/download/1.16.1/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose
          # Chrome
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          dpkg -i google-chrome-stable_current_amd64.deb
          # Spotify
          snap install spotify
          # Zoom
          wget https://zoom.us/client/5.11.10.4400/zoom_amd64.deb
          apt install ./zoom_amd64.deb
          # UNetbootin
          wget https://github.com/unetbootin/unetbootin/releases/download/702/unetbootin-linux64-702.bin
          mv unetbootin-linux64-702.bin /usr/local/bin/unetbootin
          chmod +x /usr/local/bin/unetbootin
          # apt
          echo -e "\n" | apt install -y software-properties-common
          add-apt-repository -y main
          add-apt-repository -y universe
          add-apt-repository -y restricted
          add-apt-repository -y multiverse
          add-apt-repository -y ppa:kelleyk/emacs
          apt update &
          wait
          echo -e "\n" | apt purge -y emacs* # remove old version
          echo -e "\n" | apt install -y emacs28 emacs-mozc cmigemo fcitx fcitx-mozc peco silversearcher-ag stow syncthing compton
          # Clone repositories
          mkdir /etc/skel/Project
          mkdir /etc/skel/ProjectOrg
          git clone https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/kijimaD/roam /etc/skel/roam
          cd /etc/skel/roam && git remote set-url origin git@github.com:kijimaD/roam.git
          git clone https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/kijimaD/dotfiles /etc/skel/dotfiles
          cd /etc/skel/dotfiles && git remote set-url origin git@github.com:kijimaD/dotfiles.git
          git clone https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/kijimaD/.emacs.d /etc/skel/.emacs.d
          cd /etc/skel/.emacs.d && git remote set-url origin git@github.com:kijimaD/.emacs.d.git
          git clone https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/cask/cask /etc/skel/.cask
          cd /etc/skel/.cask && git remote set-url origin git@github.com:kijimaD/.cask.git
          cd /tmp
          # Cask install
          cd /etc/skel/.emacs.d
          yes | /etc/skel/.cask/bin/cask
          cd /tmp
          # Stow
          rm -rf /etc/skel/.profile /etc/skel/.bash_logout /etc/skel/.bash_rc
          cd /etc/skel/dotfiles
          stow .
          cd /tmp
          # Check
          ls -al /
          ls -al /etc/skel
          ls -al /root
          ls -al /tmp
          check_cmd_exist () {
            type $1 >/dev/null 2>&1 && echo "$1 exists ✔"
          }
          check_cmd_exist git
          check_cmd_exist cargo
          check_cmd_exist go
          check_cmd_exist emacs
          check_cmd_exist syncthing
          check_cmd_exist compton
          check_cmd_exist stow
          check_cmd_exist google-chrome-stable
          check_cmd_exist spotify
          check_cmd_exist zoom
          check_cmd_exist unetbootin
          emacs -nw --batch --eval '(message (emacs-version))' # check version
          dpkg-query -W --showformat='${Installed-Size}\t${Package}\n' | sort -nr | head -n 100 # installed packages
          # ================
          apt clean
          rm -rf /tmp/* ~/.bash_history
          rm /etc/resolv.conf
          rm /var/lib/dbus/machine-id
          rm /sbin/initctl
          dpkg-divert --rename --remove /sbin/initctl
          umount /proc || umount -lf /proc
          umount /sys
          umount /dev/pts
          exit
          EOF
      - name: chmod
        run: chmod +w extract-cd/casper/filesystem.manifest
      - name: renew manifest
        run: sudo dpkg-query -W --showformat='${Package} ${Version}\n' > extract-cd/casper/filesystem.manifest
      - name: modify file
        run: sudo cp extract-cd/casper/filesystem.manifest extract-cd/casper/filesystem.manifest-desktop && sudo sed -i '/ubiquity/d' extract-cd/casper/filesystem.manifest-desktop && sudo sed -i '/casper/d' extract-cd/casper/filesystem.manifest-desktop
      - name: remove file
        run: sudo rm extract-cd/casper/filesystem.squashfs
      - name: mksquashfs
        run: sudo mksquashfs edit extract-cd/casper/filesystem.squashfs -b 4096
      - name: file size
        run: printf $(du -sx --block-size=1 edit | cut -f1) | sudo tee extract-cd/casper/filesystem.size
      - name: md5sum
        run: sudo rm md5sum.txt && find -type f -print0 | sudo xargs -0 md5sum | grep -v boot.catalog | sudo tee md5sum.txt
        working-directory: ./extract-cd
      - name: mkisofs
        run: sudo mkisofs -D -r -V ${{ env.CUSTOM_IMAGE_NAME }} -cache-inodes -J -l -b boot/grub/i386-pc/eltorito.img -c boot.catalog -no-emul-boot -boot-load-size 4 -boot-info-table -o ../${{ env.CUSTOM_IMAGE_ISO }} .
        working-directory: ./extract-cd
      - name: split iso
        run: split -b 1G -d ${{ env.CUSTOM_IMAGE_ISO }} ${{ env.CUSTOM_IMAGE_ISO }}-
      - name: remove original iso
        run: rm ${{ env.CUSTOM_IMAGE_ISO }}

      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: ./${{ env.CUSTOM_IMAGE_ISO }}-*

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
            gh release create ${GITHUB_REF##*/} -t "Releases ${GITHUB_REF##*/}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Release Asset
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
            gh release upload ${GITHUB_REF##*/} ./${{ env.CUSTOM_IMAGE_ISO }}-*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
