name: lint

on:
  push:
  pull_request:

jobs:
  lint-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install required packages
      run: |
        sudo apt-get install shellcheck

    - name: Check .bash_profile
      run: shellcheck ${GITHUB_WORKSPACE}/bash_profile --exclude=SC2148,SC1090

    - name: Check .bashrc
      run: shellcheck ${GITHUB_WORKSPACE}/bashrc --exclude=SC2148,SC1090
