name: 📰Release

on:
  push:
    branches:
      - main

jobs:
  # semantic-release:
  #   runs-on: ubuntu-20.04
  #   steps:
  #     - name: Checkout this repository
  #       uses: actions/checkout@v3
  #     - name: Setup node
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 18
  #     - name: Install dependencies
  #       run: yarn --frozen-lockfile
  #     - name: Releaser
  #       env:
  #         GITHUB_TOKEN: ${{ github.token }}
  #       run: yarn semantic-release

  goreleaser:
    # needs: semantic-release
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20'
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: v1.19.1
          args: release --rm-dist
          workdir: build
        env:
          GITHUB_TOKEN: ${{ github.token }}
          TAP_GITHUB_TOKEN: ${{ secrets.TAP_GITHUB_TOKEN }}
